name: observatorio
version: "1.0.0"
config-version: 2
profile: observatorio

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  observatorio:
    +materialized: view
    gold:
      +schema: gold
    dm_sst:
      +schema: dm_sst
    ops:
      +schema: ops
